# Generated by Django 4.1 on 2022-09-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('birth', models.DateField()),
                ('color', models.CharField(max_length=20)),
            ],
        ),
    ]
